from typing import TypedDict, List, Dict, Optional, Literal, Any


# ==========================================================
# Human Feedback
# Stores feedback collected from the Human Review Agent.
# Used by the Supervisor to apply user modifications.
# ==========================================================

class HumanFeedback(TypedDict):
    # Indicates whether feedback was collected
    # before prediction or after prediction.
    mode: Literal[
        "pre_prediction",
        "post_prediction"
    ]

    # User decision after reviewing the payload.
    decision: Literal[
        "approve",
        "reject",
        "retry",
        "modify"
    ]

    # Optional comments provided by the user.
    comment: Optional[str]

    # User modified fields.
    # Supervisor is responsible for applying these
    # changes back to the ReactionState.
    edited_fields: Dict[str, Any]


# ==========================================================
# Global Workflow State
# Shared by every deterministic agent.
# Updated throughout the complete workflow.
# ==========================================================

class ReactionState(TypedDict):

    # ------------------------------------------------------
    # User Request
    # Used by Supervisor Planner for intent detection.
    # ------------------------------------------------------

    user_query: str

    task_type: Literal[
        "prediction",
        "validation",
        "explanation",
    ]


    # ------------------------------------------------------
    # Input Information
    # Produced by User
    # Updated by Validator
    # ------------------------------------------------------

    # Original user supplied SMILES
    smiles: str

    # Canonicalized SMILES generated by Validator
    canonical_smiles: Optional[str]

    # User supplied reaction conditions
    conditions: Dict[str, str]


    # ------------------------------------------------------
    # Document Retrieval
    # Used by Retriever Agent
    # ------------------------------------------------------

    # Uploaded research documents
    uploaded_docs: Optional[List[str]]

    # Whether uploaded documents were ingested
    pdf_ingested: Optional[bool]

    # Indicates if external research was supplied
    external_doc_available: bool

    # Retrieved literature chunks
    retrieved_context: List[Dict[str, Any]]


    # ------------------------------------------------------
    # Prediction Output
    # Generated by Predictor Agent
    # ------------------------------------------------------

    prediction: Optional[str]

    # Prediction confidence score
    confidence: Optional[float]

    # Predicted reaction mechanism
    mechanism: Optional[str]

    # Additional prediction metadata
    prediction_metadata: Optional[
        Dict[str, Any]
    ]


    # ------------------------------------------------------
    # Verification Output
    # Generated by Verifier Agent
    # ------------------------------------------------------

    # Boolean validation results
    validation_results: Dict[str, bool]

    # Numerical validation scores
    validation_scores: Dict[str, float]


    # ------------------------------------------------------
    # Human Review
    # Filled only after Human Review Agent executes
    # ------------------------------------------------------

    human_feedback: Optional[HumanFeedback]


    # ------------------------------------------------------
    # Final Explanation
    # Generated by Explainer Agent
    # ------------------------------------------------------

    explanation_report: Optional[str]


    # ------------------------------------------------------
    # Validator Warnings
    # Displayed during Pre Prediction Review
    # ------------------------------------------------------

    warnings: List[str]


    # ------------------------------------------------------
    # Retry Tracking
    # Updated by Supervisor during retries
    # Used by Retry & Interrupt Middleware
    # ------------------------------------------------------

    retry_count: Dict[
        Literal[
            "predictor",
            "retriever",
            "verifier",
            "workflow"
        ],
        int
    ]


    # ------------------------------------------------------
    # Workflow Status
    # Updated by Supervisor after every stage
    # Useful for monitoring, logging and recovery
    # ------------------------------------------------------

    status: Literal[
        "initialized",
        "validated",
        "retrieved",
        "predicted",
        "verified",
        "retrying",
        "human_review",
        "completed",
        "failed"
    ]


    # ------------------------------------------------------
    # Current Executing Agent
    # Updated by Supervisor before invoking an agent.
    # Helps with debugging, logging and resuming execution.
    # ------------------------------------------------------

    current_agent: Optional[
        Literal[
            "validator",
            "retriever",
            "predictor",
            "verifier",
            "explainer",
            "human_review",
            "supervisor"
        ]
    ]


    # ------------------------------------------------------
    # Conversation History
    # Used by Supervisor / Explainer if conversational
    # interactions are supported in future.
    # ------------------------------------------------------

    messages: Optional[List[str]]